# Copyleft by Ekaterina Vasilieva 2021.

name: MyGitHubActions

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:


jobs:

  build:
  
    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v2

      - name: Print Hello Message
        run: echo Hello, world!

      - name: Print Hello Message
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
